security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    #VERIFICAR ROLES ACCESO
    role_hierarchy:
        ROLE_USER: [   
             #ROLE_ADMIN_***_LIST,
             #ROLE_ADMIN_***_VIEW,
             #ROLE_ADMIN_***_EDIT,
             ROLE_ADMIN         
            ]

        ROLE_ADMIN: [
            ROLE_USER
            ]

        ROLE_SUPER_ADMIN: [
            ROLE_ADMIN
            ]

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User: plaintext
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers    
    providers:
        #users_in_memory: { memory: null }
        #users_in_memory:
        #    memory:
        #        users:
        #            recon:
        #                password: recon
        #                roles: 'ROLE_ADMIN'  
        users:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            form_login:
                provider:       users
                login_path:     admin_login
                use_forward:    false
                check_path:     admin_login
                failure_path:   null
            logout:
                path:           admin_logout
                target:         admin_login
            anonymous:          true
            guard:
                authenticators:
                - App\Security\LoginAuthenticator            
            
        main:
            anonymous: lazy
            #provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }    
    - { path: ^/admin/, role: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
    #- { path: ^/admin/app/, role: [ROLE_USER, ROLE_ADMIN] }
    #- { path: ^/admin/app/user/, role: [ROLE_SUPER_ADMIN] }    
    - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
