sonata_admin:
    title: 'LaborTerapia'
    title_logo: img/challenge.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            admin:            
                roles: [ ROLE_USER ]
            inventario_mas:
                label: Inventario Viejo
                roles: [ ROLE_USER ]                
            inventario:
                label: Inventario Actual
                roles: [ ROLE_USER ]
            #totales:
            #    roles: [ROLE_SUPER_ADMIN]
            #    label: Totales
            #    items:
            #        - route: admin_app_objetoinventariototales_total
            #          label: Totales
            
    options:
        legacy_twig_text_extension: false

    security:
        handler: sonata.admin.security.handler.role
        #role_user: ROLE_ADMIN
        #role_admin: ROLE_ADMIN
        #role_super_admin: ROLE_SUPER_ADMIN
        #role_super_admin: ROLE_SUPER_ADMIN

    templates:
        layout: 'standard_layout.html.twig'        

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
